### ISSUE TITLE
Theme Issue installation

### ISSUE THREAD

**Issue by ProfessorYehoshua** [justindsmith/little-ocean#1]
Hi Justin,

I have been trying to install/use your theme with a new hugo project after following down all the different rabbit holes of evergreen note taking.

I'm not sure if its the build, or adding little-ocean to my themes wrong, but I am receiving an error every time I try to "hugo server".

<img width="1220" alt="Capture" src="https://github.com/justindsmith/little-ocean/assets/74394286/5ad453a4-905d-4f19-8947-6498d8061a58">

Do you have input for someone trying to use your template to improve their productivity?  I guess I shouldn't get too ahead of myself if I can't get it passed the themes section. 

Thanks!

**Comment by justindsmith** [comment]
Hey Josh! What version of hugo are you using? I can try to verify things on my local to see if I can reproduce the error.

**Comment by ProfessorYehoshua** [comment]
> Hey Josh! What version of hugo are you using? I can try to verify things on my local to see if I can reproduce the error.

Sorry for the late reply. 

![image](https://github.com/justindsmith/little-ocean/assets/74394286/3055dc6a-9cfc-48a5-9fe7-fd7eb69c51b7)

I am very new to Hugo, but maybe I can get your assistance in getting your theme ported over - and then I can PR and update the readme if you'll allow it.

In order to get a theme ported over in hugo - do I just change my theme in the config file once your theme is in my themes folder? 

However - if I can't get it to work, I guess I can use Obsidian and "Andy Mode".

Hope you enjoyed your weekend!

**Comment by justindsmith** [comment]
Hmm... seems weird. I'd say upgrade your `hugo` version (yours is a couple years old) and try again. If that doesn't work, let me know what steps you did to install the template in your hugo server (here are the offical docs for installation: https://gohugo.io/getting-started/quick-start/#commands)

**Comment by ProfessorYehoshua** [comment]
> Hmm... seems weird. I'd say upgrade your `hugo` version (yours is a couple years old) and try again. If that doesn't work, let me know what steps you did to install the template in your hugo server (here are the offical docs for installation: https://gohugo.io/getting-started/quick-start/#commands)

I upgraded my HUGO Version to the most recent - extended version and surprise!! - It works.

Thank you for helping me. (sorry for creating an issue on your repo - I just really wanted to learn how to use this theme, and I didn't know how else to reach you).

I really do appreciate the help you've given me. 

Now time to learn some HUGO and note taking.

**Comment by justindsmith** [comment]
Glad you got it working! Good luck and have fun! 🙂

**Comment by ProfessorYehoshua** [comment]
Hey Justin,

I'm running into a separate issue where my images aren't being called in markdown. 

I'm not sure what I'm doing wrong - I'll post a link to the repo, and the netlify domain it's being hosted on.

Was just wondering if you could help answer what a couple lines of the code do. Specifically the ones that change "-" in file names. Some of my file names have "-" in them, not sure if that's the issue.

Hope you've been well over the last two months since we've last spoke!

**Comment by justindsmith** [comment]
Hello! Sorry you're seeing issues. The only change of "-" that I can find is in this file: https://github.com/justindsmith/little-ocean/blob/main/archetypes/default.md?plain=1#L2

Are you seeing the change anywhere else? That files _shouldn't_ impact images, it's more about meta-data generation for the name of the page.

**Comment by ProfessorYehoshua** [comment]
Hi Justin!

I believe it may have been from me having conflicting folder paths as the
two other "theme files" since I was following your naming convention as I
was learning.

I believe it may have been looking in your folders
"static/note-images/.png" (not proper web dev skills but I just included
them all in the same folder and it worked).

So I guess I found a fix/work around hahaha, did this open as a new issue
or did is it still closed?

Thank you so much - always!

**Comment by justindsmith** [comment]
Glad you got this resolved! :) This wasn't a new issue, still closed, but feel free to ping me here if anything comes up.

**Comment by ProfessorYehoshua** [comment]
Hi Justin -

I have a question. I'm not sure why I didn't write down the steps for the
website.

I'm trying to now use your template to create my own digital garden - for
my own notes. But god - I don't remember the steps at all.

hugo new site quickstart cd quickstart git init git submodule add
https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke echo
"theme = 'ananke'" >> hugo.toml hugo server
using those steps.

Do I do the echo theme here?

I forked your repo - and its sitting at.
https://github.com/ProfessorYehoshua/digital-garden

So would I do

hugo new site digital-garden
cd digital-garden
git init
git submodule add https://github.com/ProfessorYehoshua/digital-garden
themes/digital-garden
echo "theme = 'digital-garden'" >> hugo.toml
hugo server

?

I honestly don't remember the steps to get it up and running - I was going
to just copy what I have locally from my other site - but if you have a
second - I'd like to make sure I understand the proper way of doing it.
